import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Hero from "../components/Hero";
import Box from "../components/Box";
import ListItem from "../components/ListItem";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Hero>
					<div className="max-w-sm text-center lg:text-left">
						<p className="mb-8 font-bold text-green-700">HOME</p>
						<h1 className="text-4xl md:text-56 font-bold text-green-900 leading-snug">
							GoGreenly®
						</h1>
						<h1 className="text-4xl md:text-56 font-light text-green-900 leading-tight">
							Garden Care & Lawn Maintenance
						</h1>

						<p className="font-normal text-lg text-green-900 mt-8">
							Your Eco-Friendly Lawn & Garden Specialists
						</p>
						<div className="mt-10">
							<Link href="/book">
								<a className="px-6 rounded-md bg-green-700 hover:bg-gray-800 text-white font-medium py-3 ">
									Our Pricing
								</a>
							</Link>
							<Link href="/book">
								<a className="px-6 ml-4 rounded-md bg-gray-100 hover:bg-gray-300 text-black font-medium py-3 ">
									Book now
								</a>
							</Link>
						</div>
					</div>
					<div className="hidden lg:block">
						<Image src={require("../media/greenhouse.png")} />
					</div>
				</Hero>
				<Box>
					<div className="hidden lg:block max-w-lg w-full h-auto relative">
						<Image
							src={require("../media/tree-in-greenhouse.png")}
							objectFit="cover"
							layout="fill"
						/>
					</div>
					<div className="flex-1 flex items-center justify-center py-28 text-center lg:text-left px-2 md:px-3 lg:px-5">
						<div className="max-w-2xl">
							<p className="font-bold text-green-700 mb-8">
								LAWN AND GRASS GREENING
							</p>
							<h1 className="text-3xl md:text-5xl font-semibold text-green-800 leading-tight mb-8">
								Take care of your lawn and garden while taking care of the
								environment.
							</h1>
							<h2 className="italic text-xl md:text-2xl font-normal text-green-800 mb-8">
								The GoGreenly Team pride themselves on completing lawn and
								garden jobs fast and leave your home or business looking
								stellar.
							</h2>
							<p className="font-normal text-green-800 mb-8">
								Working with all electric tools, we spare you and your
								neighbours the headache and the unpleasant smells that come with
								traditional garden tools. Combined with organic weed killer and
								fertiliser, we keep your property safe for kids and pets.
							</p>
							<ul className="text-left text-green-800 font-normal">
								<ListItem>
									All electric tools with{" "}
									<span className="font-bold">low noise and no smells</span>
								</ListItem>
								<ListItem>
									All electric tools with{" "}
									<span className="font-bold">low noise and no smells</span>
								</ListItem>
								<ListItem>
									All electric tools with{" "}
									<span className="font-bold">low noise and no smells</span>
								</ListItem>
								<ListItem>
									All electric tools with{" "}
									<span className="font-bold">low noise and no smells</span>
								</ListItem>
								<ListItem>
									All electric tools with{" "}
									<span className="font-bold">low noise and no smells</span>
								</ListItem>
							</ul>
						</div>
					</div>
				</Box>
				<div className="bg-gray-50 font-montserrat md:pb-32">
					<div className="flex items-center justfily-between max-w-6xl mx-auto px-3 sm:px-6 xl:px-2 py-16">
						<div className="flex-1 px-4 text-center lg:text-left">
							<p className="font-bold text-green-700 mb-8">PRICING</p>
							<h1 className="text-3xl md:text-5xl font-semibold text-green-800 leading-tight mb-8">
								Transparent pricing
							</h1>
							<h2 className="italic text-xl md:text-2xl font-normal text-green-800 mb-12">
								Most one-off services are billed at $60 per hour, ‘per gardener
								with a minimum billing time of 60 minutes . Nice and simple.
							</h2>
							<h1 className="text-2xl md:text-3xl font-semibold text-green-800 leading-tight mb-8">
								What on earth is grass greening?
							</h1>
							<p className="font-normal text-green-800 mb-8">
								Grass greening is a flat rate based on the size of the property
								because consumable resources are required.
							</p>
							<Link href="/grass-greening">
								<a className="underline font-normal text-green-800">
									Find out here
								</a>
							</Link>
						</div>
						<div className="hidden lg:block">
							<Image src={require("../media/image-circle.png")} />
						</div>
					</div>
				</div>
				<div className="md:-mt-32 font-montserrat">
					<div className="max-w-6xl mx-auto px-3 sm:px-6 xl:px-2">
						<div>
							<Image
								src={require("../media/castle.png")}
								objectFit="cover"
								layout="responsive"
								className="filter brightness-50"
							/>
						</div>
						<div className="md:flex justify-between py-24">
							<h1 className="lg:max-w-xs text-3xl md:text-5xl font-semibold text-green-800 leading-tight mb-8">
								Need us to do a job?
							</h1>
							<div>
								<h2 className="italic text-2xl font-normal text-green-800 mb-8">
									GoGreenly are your garden experts. Get boots on the ground to
									sort out your garden.{" "}
									<span className="font-bold">Book our team today.</span>
								</h2>
								<p className="font-normal mb-8 text-green-800">
									Want to keep your carbon footprint low? We’ll arrive ready to
									get your commercial or residential garden looking like a treat
									using natural products and eco-friendly tools.
								</p>
								<div className="mt-10">
									<Link href="/book">
										<a className="px-6 rounded-md bg-green-700 hover:bg-gray-800 text-white font-medium py-3 ">
											Our Pricing
										</a>
									</Link>
									<Link href="/book">
										<a className="px-6 ml-4 rounded-md bg-gray-100 hover:bg-gray-300 text-black font-medium py-3 ">
											Book now
										</a>
									</Link>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div className="bg-gray-100 font-montserrat">
					<div className="max-w-6xl mx-auto px-3 sm:px-6 xl:px-2 ">
						<div className="py-24 flex flex-col lg:flex-row items-center text-center lg:text-left border-b border-green-800">
							<Image src={require("../media/svg/union.svg")} />
							<h2 className="flex-1 text-2xl md:text-5xl font-semibold text-green-800 leading-tight lg:ml-16 mt-12 lg:mt-0">
								Get exactly what you need from our range of specialised lawn and
								garden services. GoGreenly are your garden experts.
							</h2>
						</div>
						<div className="py-24 max-w-xl">
							<h2 className="text-2xl md:text-3xl font-semibold text-green-800 leading-tight mb-8">
								Let us know which jobs you want handled and we’ll send our team
								out.
							</h2>
							<h3 className="text-green-800 italic text-lg md:text-2xl mb-8">
								We deliver industry-leading lawn care and garden transformations
								to both commercial and residential clients at standardised and
								fully transparent prices.
							</h3>
							<p className="text-green-800 font-normal">
								Built on strong values of excellence, expertise, transparency,
								and satisfaction, we’re driven to deliver great gardens that
								delight our customers. Best of all we’re environmentally
								friendly, plus our prices are transparent so you know you’re
								paying the same as someone for a similar job.
							</p>
						</div>
					</div>
				</div>
			</main>
		</div>
	);
}
